definitions:
  models.Pessoa:
    properties:
      idade:
        type: integer
      nome:
        type: string
    type: object
info:
  contact: {}
paths:
  /pessoas:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Pessoa'
            type: array
      summary: retorna pessoas
swagger: "2.0"
